spring:
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSS'Z'
    serialization:
      write_dates_as_timestamps: false
    default-property-inclusion: non_null
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 5
    name: sharding-sphere-demo
    test-on-borrow: true
    url: jdbc:mysql://127.0.0.1:3306/sharding_sphere_demo
    username: root
    password: root
    validation-query: SELECT 1
    test-while-idle: true
  flyway:
    locations: classpath:/db/migration
    out-of-order: true
